using System.Text.Json.Serialization;
using Mintlify.Core.Converters;

namespace Mintlify.Core.Models
{

    /// <summary>
    /// Represents the API reference configuration and playground settings for Mintlify.
    /// </summary>
    /// <remarks>
    /// This configuration controls how API documentation is displayed and how the API playground
    /// functions, including OpenAPI, AsyncAPI, and MDX-based API specifications.
    /// </remarks>
    public class ApiConfig
    {

        #region Properties

        /// <summary>
        /// Gets or sets the AsyncAPI specification configuration.
        /// </summary>
        /// <remarks>
        /// Can be a string URL, an array of URLs, or an object with source and directory properties
        /// pointing to AsyncAPI specification files.
        /// </remarks>
        [JsonPropertyName("asyncapi")]
        [JsonConverter(typeof(ApiConfigConverter))]
        public object? AsyncApi { get; set; }

        /// <summary>
        /// Gets or sets the configuration for autogenerated API examples.
        /// </summary>
        /// <remarks>
        /// Controls which programming languages are shown in code examples and whether
        /// optional parameters are included in the generated examples.
        /// </remarks>
        [JsonPropertyName("examples")]
        public ApiExamplesConfig? Examples { get; set; }

        /// <summary>
        /// Gets or sets the MDX configuration for API pages generated from MDX files.
        /// </summary>
        /// <remarks>
        /// Allows manual definition of API endpoints in individual MDX files rather than
        /// using an OpenAPI specification. Useful for small APIs or prototyping.
        /// </remarks>
        [JsonPropertyName("mdx")]
        public MdxConfig? Mdx { get; set; }

        /// <summary>
        /// Gets or sets the OpenAPI specification configuration.
        /// </summary>
        /// <remarks>
        /// Can be a string URL, an array of URLs, or an object with source and directory properties
        /// pointing to OpenAPI specification files.
        /// </remarks>
        [JsonPropertyName("openapi")]
        [JsonConverter(typeof(ApiConfigConverter))]
        public object? OpenApi { get; set; }

        /// <summary>
        /// Gets or sets the display settings for API parameters.
        /// </summary>
        /// <remarks>
        /// Controls how API parameters are displayed in the documentation,
        /// including whether they are expanded by default.
        /// </remarks>
        [JsonPropertyName("params")]
        public ApiParamsConfig? Params { get; set; }

        /// <summary>
        /// Gets or sets the API playground settings.
        /// </summary>
        /// <remarks>
        /// Controls the display mode of the API playground and whether requests
        /// are proxied through Mintlify's servers for CORS handling.
        /// </remarks>
        [JsonPropertyName("playground")]
        public ApiPlaygroundConfig? Playground { get; set; }

        /// <summary>
        /// Gets or sets whether to pass API requests through a proxy server.
        /// </summary>
        /// <remarks>
        /// When true, API requests from the playground are routed through Mintlify's
        /// proxy servers to handle CORS restrictions. This is a legacy property that
        /// is superseded by Playground.Proxy but kept for backward compatibility.
        /// Defaults to true when not specified.
        /// </remarks>
        [JsonPropertyName("proxy")]
        public bool? Proxy { get; set; }

        #endregion

    }

}