using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Mintlify.Core.Models
{

    /// <summary>
    /// Represents the configuration for autogenerated API examples in the documentation.
    /// </summary>
    /// <remarks>
    /// Controls which programming languages are shown in code examples and whether
    /// optional parameters are included in the generated examples.
    /// </remarks>
    public class ApiExamplesConfig
    {

        #region Properties

        /// <summary>
        /// Gets or sets whether to show optional parameters in API examples.
        /// </summary>
        /// <remarks>
        /// Valid values are:
        /// - "all": Show all parameters including optional ones
        /// - "required": Show only required parameters
        /// Defaults to "all" when not specified.
        /// </remarks>
        /// <example>
        /// <code>
        /// "examples": {
        ///   "defaults": "required"
        /// }
        /// </code>
        /// </example>
        [JsonPropertyName("defaults")]
        public string? Defaults { get; set; }

        /// <summary>
        /// Gets or sets the programming languages for autogenerated API snippets.
        /// </summary>
        /// <remarks>
        /// Specifies which programming languages should be included in the
        /// automatically generated code examples. Common values include:
        /// "javascript", "python", "curl", "go", "java", "php", "ruby", etc.
        /// </remarks>
        /// <example>
        /// <code>
        /// "examples": {
        ///   "languages": ["javascript", "python", "curl"]
        /// }
        /// </code>
        /// </example>
        [JsonPropertyName("languages")]
        public List<string>? Languages { get; set; }

        #endregion

    }

}